# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a32ed5bc1f4ff68ddcfbbedb12a53de7c725b5db36dc123f9c27fbac0fb2dde0b34b52fd2b4262741b5c0f9597098a11f95d1c31b773106bf55fa5c772bf7d94

test:
  secret_key_base: a7629018a4c78e73141632f9ac65b8d58a678ada24382d87637447852b01ff0a98554ed5909e99064a058d4d4cf2b5d64beb6f5aa639323ef86f1831b2c3cbe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
